// new message arrival
#define _NOTIFICATION_NEW_MESSAGE_RECEIVED @"_NOTIFICATION_NEW_MESSAGE_RECEIVED"
#define _NOTIFICATION_NEW_MESSAGE_ADDED @"_NOTIFICATION_NEW_MESSAGE_ADDED"

// message has been marked as read
// object: a message marked as read or nil (there's no unread message)
#define _NOTIFICATION_MESSAGE_STATUS_MARKED_AS_READ @"_NOTIFICATION_MESSAGE_STATUS_MARKED_AS_READ"

// message view change
#define _NOTIFICATION_MESSAGE_VIEW_CHANGING @"_NOTIFICATION_MESSAGE_VIEW_CHANGING"
#define _NOTIFICATION_MESSAGE_VIEW_CHANGED @"_NOTIFICATION_MESSAGE_VIEW_CHANGED"

// look & feels
#define _NOTIFICATION_COLOR_SCHEME_CHANGED @"_NOTIFICATION_COLOR_SCHEME_CHANGED"
#define _NOTIFICATION_WINDOW_ALPHA_CHANGED @"_NOTIFICATION_WINDOW_ALPHA_CHANGED"
#define _NOTIFICATION_FONT_SIZE_CHANGED @"_NOTIFICATION_FONT_SIZE_CHANGED"
#define _NOTIFICATION_FONT_SIZE_CHANGED2 @"_NOTIFICATION_FONT_SIZE_CHANGED2"

// object: true - changed to display / false - change to hide
#define _NOTIFICATION_STATISTICS_DISPLAY_SETTING_CHANGED @"_NOTIFICATION_STATISTICS_DISPLAY_SETTING_CHANGED"

#define _NOTIFICATION_SEND_MESSAGE_WITH_ENTER_AND_MODIFIER_SETTING_CHANGED @"_NOTIFICATION_SEND_MESSAGE_WITH_ENTER_AND_MODIFIER_SETTING_CHANGED"