// see http://twitter.com/oauth_clients

// SpeakTweet
#define TWITTER_OAUTH_CONSUMER_KEY			@"7aM247rLdfQQjLb6X5dZQ"
#define TWITTER_OAUTH_CONSUMER_SECRET		@"Ls4cySGy5nckZ5rlHsyR4By3IVjANdeC1tOKKXPz8"


// SpeakTweet
#define TWITTER_OAUTH_CONSUMER_KEY_old			@"ORdJ0f4FCYis4yJxAZb1w"
#define TWITTER_OAUTH_CONSUMER_SECRET_old		@"IbUAz976jJW5hPAQE43yXcW30MQO32PBA9OPv9EprCc"

// iSteve
#define TWITTER_OAUTH_CONSUMER_KEY_			@"MCnyKoyIKReB3DCvzyyQ"
#define TWITTER_OAUTH_CONSUMER_SECRET_		@"nMwXCbUA68ILnFMV98Owgn2diSbEVDs44veGbf7ZY"